#ifdef __cplusplus
extern "C" {
#endif

spStringTable sw_string_table[] = {
    {SW_MENU_FILE_LABEL_ID, "&File"},
    {SW_MENU_OPEN_LABEL_ID, "&Open..."},
    {SW_MENU_SAVE_LABEL_ID, "&Save"},
    {SW_MENU_CLOSE_LABEL_ID, "&Close"},
    {SW_MENU_QUIT_LABEL_ID, "E&xit"},
    
    {SW_MENU_OPEN_NEW_LABEL_ID, "Open &New..."},
    {SW_MENU_SAVE_AS_LABEL_ID, "Save &As..."},
    {"SW_MENU_GENERATE_LABEL", "&Generate..."},
    
    {SW_MENU_OPEN_DESC_ID, "Open a file in the current window"},
    {SW_MENU_OPEN_NEW_DESC_ID, "Open a file in the new window"},
    {SW_MENU_SAVE_DESC_ID, "Save this file"},
    {SW_MENU_SAVE_AS_DESC_ID, "Save a copy of this file"},
    
    {"SW_MENU_PROPERTY_LABEL", "Propert&y..."},
    
    {"SW_MENU_PAGE_SETUP_LABEL", "Page Set&up..."},
    {"SW_MENU_PRINT_LABEL", "&Print..."},
    {"SW_MENU_PRINT_TARGET_LABEL", "Print &Target"},
	
    {SW_MENU_PAGE_LABEL_ID, "&Page"},
    {SW_MENU_FORWARD_LABEL_ID, "&Forward"},
    {SW_MENU_BACKWARD_LABEL_ID, "&Backward"},
    {SW_MENU_GO_HEAD_LABEL_ID, "&Head"},
    {SW_MENU_GO_TAIL_LABEL_ID, "&Tail"},
    {SW_MENU_NEXT_WINDOW_LABEL_ID, "&Next Window"},
    {SW_MENU_PREV_WINDOW_LABEL_ID, "&Previous Window"},
    {SW_MENU_ALIGN_WINDOW_LABEL_ID, "A&lign"},
    {SW_MENU_SELECT_REGION_LABEL_ID, "&Select"},
    {SW_MENU_SELECT_ALL_REGION_LABEL_ID, "Select Same &Region"},
    {SW_MENU_SELECT_ALL_LABEL_ID, "Select &All"},
    {SW_MENU_SELECT_NEXT_CHANNEL_LABEL_ID, "Select Next &Channel"},
    {SW_MENU_SELECT_FROM_HERE_LABEL_ID, "Select Fro&m Here"},
    {SW_MENU_SELECT_TO_HERE_LABEL_ID, "Select T&o Here"},
    
    {SW_MENU_VIEW_LABEL_ID, "&View"},
    {SW_MENU_ZOOM_IN_LABEL_ID, "Zoom &In"},
    {SW_MENU_ZOOM_OUT_LABEL_ID, "Zoom &Out"},
    {SW_MENU_ZOOM_FULL_OUT_LABEL_ID, "Zoom &Full Out"},
    {SW_MENU_ZOOM_REGION_LABEL_ID, "Zoom &Region"},
    {SW_MENU_ZOOM_IN_AMPLITUDE_LABEL_ID, "Zoom In Vertical Axis"},
    {SW_MENU_ZOOM_OUT_AMPLITUDE_LABEL_ID, "Zoom Out Vertical Axis"},
    {SW_MENU_ZOOM_FULL_OUT_AMPLITUDE_LABEL_ID, "Zoom Full Out Vertical Axis"},
    {SW_MENU_ALIGN_AMPLITUDE_LABEL_ID, "Align Vertical Axis"},
    {SW_MENU_DISPLAY_INFO_AREA_LABEL_ID, "Display Information &Area"},
    {SW_MENU_DRAW_DETAIL_LABEL_ID, "Draw &Detail"},
    {SW_MENU_DRAW_LABEL_LABEL_ID, "Draw &Labels"},
    {SW_MENU_LOG_FREQUENCY_AXIS_LABEL_ID, "Log Fre&quency Axis"},
    {SW_MENU_SPECTROGRAM_LABEL_ID, "Spectro&gram"},
    {SW_MENU_NO_SPECTROGRAM_LABEL_ID, "N&o Spectrogram"},
    {SW_MENU_WIDE_SPECTROGRAM_LABEL_ID, "&Wide Band Spectrogram"},
    {SW_MENU_NARROW_SPECTROGRAM_LABEL_ID, "&Narrow Band Spectrogram"},
    {SW_MENU_NARROW_SMOOTHED_SPECTROGRAM_LABEL_ID, "S&moothed Spectrogram"},
    {SW_MENU_CQT_SPECTROGRAM_LABEL_ID, "C&QT Spectrogram"},
    {SW_MENU_UPDATE_SPECTROGRAM_LABEL_ID, "&Update Spectrogram"},
    {SW_MENU_SPECTROGRAM_DIALOG_LABEL_ID, "Spectrogram &Setting..."},
    {SW_MENU_SPECTROGRAM_DRAW_KEYS_LABEL_ID, "Draw &Piano Keyboard"},
    
    {SW_MENU_ANALYSIS_SUBPLOT_LABEL_ID, "Sub&plot Analysis Result"},
    {SW_MENU_ANALYSIS_SUBPLOT_SPECTROGRAM_LABEL_ID, "&Spectrogram"},
    {SW_MENU_ANALYSIS_SUBPLOT_F0_LABEL_ID, "&Fundamental Frequency"},
    {SW_MENU_ANALYSIS_SUBPLOT_POWER_LABEL_ID, "&Power"},
    {SW_MENU_ANALYSIS_SUBPLOT_APERIODICITY_LABEL_ID, "&Aperiodicity"},
    {SW_MENU_ANALYSIS_SUBPLOT_STRAIGHT_SPECGRAM_LABEL_ID, "ST&RAIGHT Spectrogram"},
    {SW_MENU_ANALYSIS_SUBPLOT_STRAIGHT_F0_LABEL_ID, "STRAIG&HT F0"},
	
    {SW_MENU_TIME_FORMAT_LABEL_ID, "&Time Format"},
    {SW_MENU_TIME_FORMAT_SEC_LABEL_ID, "&Second"},
    {SW_MENU_TIME_FORMAT_MSEC_LABEL_ID, "&Milli Second"},
    {SW_MENU_TIME_FORMAT_POINT_LABEL_ID, "&Point"},
    {SW_MENU_TIME_FORMAT_SEPARATED_SEC_LABEL_ID, "Sepa&rated Second"},
    
    {SW_MENU_PLAY_DESC_ID, "Play the selected region"},
    {SW_MENU_LOOP_PLAY_DESC_ID, "Enable loop play of the selected region"},
    {SW_MENU_SYNC_PLAY_DESC_ID, "Enable autoscroll synchronized with playing region"},
    {SW_MENU_PLAY_STOP_DESC_ID, "Stop processing"},
    {SW_MENU_FORWARD_DESC_ID, "Forward page"},
    {SW_MENU_BACKWARD_DESC_ID, "Backward page"},
    {SW_MENU_GO_HEAD_DESC_ID, "Go to the head"},
    {SW_MENU_GO_TAIL_DESC_ID, "Go to the tail"},
    {SW_MENU_ZOOM_IN_DESC_ID, "Zoom in"},
    {SW_MENU_ZOOM_OUT_DESC_ID, "Zoom out"},
    {"SW_MENU_PAUSE_CURSOR_DESC", "Pause cursor of this window"},
    
    {SW_MENU_EDIT_LABEL_ID, "&Edit"},
    {SW_MENU_UNDO_LABEL_ID, "&Undo"},
    {SW_MENU_REDO_LABEL_ID, "&Redo"},
    {SW_MENU_CUT_LABEL_ID, "&Cut"},
    {SW_MENU_COPY_LABEL_ID, "Cop&y"},
    {SW_MENU_CLIPBOARD_WINDOW_LABEL_ID, "C&lipboard Window..."},
    {SW_MENU_CROP_LABEL_ID, "C&rop"},
    {SW_MENU_DELETE_LABEL_ID, "&Delete"},
    {SW_MENU_ERASE_LABEL_ID, "Era&se"},
    {SW_MENU_EXTRACT_LABEL_ID, "E&xtract"},
    {SW_MENU_EXTRACT_AUTOSAVE_LABEL_ID, "Extract and &Autosave"},
    {SW_MENU_SAVE_BY_NORMAL_LABEL_LABEL_ID, "Save by Normal Label..."},
    {SW_MENU_SAVE_BY_REGION_LABEL_LABEL_ID, "Save by Region Label..."},
    {SW_MENU_INVERT_LABEL_ID, "In&vert"},
    {SW_MENU_AMPLIFY_LABEL_ID, "A&mplify..."},
    {SW_MENU_NORMALIZE_LABEL_ID, "&Normalize..."},
    {SW_MENU_FADE_IN_LABEL_ID, "Fade &In"},
    {SW_MENU_FADE_OUT_LABEL_ID, "Fade &Out"},
    {SW_MENU_CHANNEL_SWAP_LABEL_ID, "Channel S&wap"},
    
    {SW_MENU_MAXIMIZE_LABEL_ID, "Maximize..."},
    {SW_MENU_SAMP_RATE_CONV_LABEL_ID, "Sampling &Frequency Conversion..."},
    {SW_MENU_CHANNEL_CONV_LABEL_ID, "C&hannel Conversion..."},
    {SW_MENU_BIT_CONV_LABEL_ID, "&Bits/Sample Conversion..."},
    {SW_MENU_MONAURALIZE_LABEL_ID, "Monaurali&ze"},
    {"SW_MENU_FILTERING_LABEL", "Filterin&g..."},
    
    {SW_MENU_CLIPBOARD_LABEL_ID, "&Clipboard"},
    {SW_MENU_PASTE_LABEL_ID, "&Paste"},
    {SW_MENU_INSERT_LABEL_ID, "&Insert"},
    {SW_MENU_CAT_LABEL_ID, "Concatenate to &Tail"},
    {SW_MENU_CATTOP_LABEL_ID, "Concatenate to &Head"},
    {SW_MENU_MIX_LABEL_ID, "&Mix"},
    {SW_MENU_REPLACE_LABEL_ID, "&Replace"},
    {SW_MENU_INSERT_PAUSE_LABEL_ID, "Insert Pa&use..."},
    {SW_MENU_CHANGE_VALUE_LABEL_ID, "Change &Value..."},
    
    {SW_MENU_HELP_LABEL_ID, "&Help"},
    {SW_MENU_DISPLAY_HELP_LABEL_ID, "&Contents"},
    {SW_MENU_INFO_LABEL_ID, "&About"},
    {SW_MENU_PLUGIN_INFO_LABEL_ID, "&Plugin Information"},

    {SW_MENU_SOUND_LABEL_ID, "&Sound"},
    
    {SW_MENU_PLAY_LABEL_ID, "&Play Selected Region"},
    {SW_MENU_PLAY_WINDOW_LABEL_ID, "Play &Window Contents"},
    {SW_MENU_PLAY_FILE_LABEL_ID, "Play En&tire File"},
    {SW_MENU_RECORD_LABEL_ID, "&Record to Selected Region"},
    {SW_MENU_PLAY_STOP_LABEL_ID, "&Stop Processing"},
    {SW_MENU_LOOP_PLAY_LABEL_ID, "Enable &Loop Play"},
    {SW_MENU_SYNC_PLAY_LABEL_ID, "Enable S&ynchronous Play"},
    {"SW_MENU_PAUSE_CURSOR_LABEL", "Pa&use Cursor"},
    
    {SW_MENU_ANALYSIS_PREFERENCE_LABEL_ID, "Preference for &Analysis..."},
    {SW_MENU_ANALYSIS_LABEL_ID, "&Analysis"},
    {SW_MENU_ANALYSIS_REGION_LABEL_ID, "Analysis of Selected Region"},
    {SW_MENU_ANALYSIS_WIDE_LABEL_ID, "&Wide Band Analysis"},
    {SW_MENU_ANALYSIS_NARROW_LABEL_ID, "&Narrow Band Analysis"},
    {SW_MENU_ANALYSIS_CQT_LABEL_ID, "C&QT Analysis"},
    
    {SW_MENU_PREFERENCE_LABEL_ID, "&Preference..."},
    {SW_MENU_INFO_DIALOG_LABEL_ID, "File Metadata..."},

    {SW_MENU_LABEL_LABEL_ID, "&Label"},
    {SW_MENU_OPEN_LABEL_LABEL_ID, "&Open Label..."},
    {SW_MENU_SAVE_LABEL_LABEL_ID, "&Save Label"},
    {SW_MENU_SAVE_AS_LABEL_LABEL_ID, "Save Label &As ..."},
    {SW_MENU_CLEAR_LABEL_LABEL_ID, "&Clear Label"},
    {SW_MENU_OPEN_REGION_LABEL_LABEL_ID, "&Open Region Label..."},
    {SW_MENU_SAVE_REGION_LABEL_LABEL_ID, "&Save Region Label"},
    {SW_MENU_SAVE_AS_REGION_LABEL_LABEL_ID, "Save Region Label &As ..."},
    {SW_MENU_CLEAR_REGION_LABEL_LABEL_ID, "&Clear Region Label"},
    
    {SW_MENU_INSERT_SIMPLE_LABEL_LABEL_ID, "Insert &Simple Label"},
    {SW_MENU_INSERT_VALUE_LABEL_LABEL_ID, "Insert Label with &Value"},
    {SW_MENU_INSERT_LABEL_LABEL_ID, "&Insert Label..."},
    {SW_MENU_CHANGE_LABEL_LABEL_ID, "&Change Label..."},
    {SW_MENU_ERASE_LABEL_LABEL_ID, "&Erase Label"},
    {SW_MENU_ERASE_LABEL_REGION_LABEL_ID, "Erase Label in Selected Re&gion"},
    {SW_MENU_SELECT_BETWEEN_LABELS_LABEL_ID, "Select &Between Labels"},
    {SW_MENU_SET_REGION_LABEL_LABEL_ID, "Set &Region Label"},
    {SW_MENU_SET_REGION_LABEL_AS_REGION_LABEL_ID, "Set Region Label &As Current Region"},
    {SW_MENU_CAT_REGION_LABELS_LABEL_ID, "C&oncatenate Region Labels"},
    {SW_MENU_DIVIDE_REGION_LABEL_LABEL_ID, "&Divide Region Label"},
    
    {SW_OPEN_DIALOG_TITLE_ID, "Open..."},
    {SW_SAVE_DIALOG_TITLE_ID, "Save As..."},
    
    {SW_ERROR_TITLE_ID, "Error"},
    {SW_WARNING_TITLE_ID, "Warning"},
    {SW_INFO_TITLE_ID, "About"},
    
    {SW_AUDIO_DEVICE_ERROR_MESSAGE_ID, "Audio device error occurred."},
    {SW_EDIT_ERROR_MESSAGE_ID, "Can't edit this file."},
    {SW_REGION_ERROR_MESSAGE_ID, "Please set a region."},
    {SW_DELETE_WHOLE_ERROR_MESSAGE_ID, "Can't delete the whole file."},
    {SW_PLAY_ERROR_MESSAGE_ID, "Can't play this file."},
    {SW_PLAY_LONG_ERROR_MESSAGE_ID, "The playback region is too long."},
    {SW_LOOP_PLAY_SHORT_ERROR_MESSAGE_ID, "The playback region is too short for loop."},
    
    {SW_CB_NOT_FOUND_ERROR_MESSAGE_ID, "Can't find clipboard contents."},
    {SW_CB_PROCESSING_ERROR_MESSAGE_ID, "The clipboard is in use.\nPlease wait until the processing is completed."},
    {SW_CB_DIFFERENT_CHANNEL_ERROR_MESSAGE_ID, "The number of channels is different from clipboard's one."},
    {SW_CB_DIFFERENT_SAMP_RATE_ERROR_MESSAGE_ID, "The sampling frequency is different from clipboard's one."},
    
    {SW_ANALYSIS_ERROR_MESSAGE_ID, "Can't analyze this file."},
    {SW_ANALYSIS_LONG_ERROR_MESSAGE_ID, "The analysis region is too long."},

    {SW_OPEN_ERROR_MESSAGE_ID, "Can't open file: %s"},
    {SW_SAVE_ERROR_MESSAGE_ID, "Can't save file."},
    {SW_PLUGIN_ERROR_MESSAGE_ID, "Can't load plugin."},
    {SW_PLUGIN_NOT_FOUND_MESSAGE_ID, "Can't save file in this format.\nSelect another format."},
    {SW_FORMAT_NOT_SUPPORTED_MESSAGE_ID, "The format is probably not supported."},
    {SW_SAVE_FIRST_ERROR_MESSAGE_ID, "You have to save this file first."},
    {SW_FILE_NOT_EXIST_ERROR_MESSAGE_ID, "Can't find file: %s"},
	 
    {SW_SUFFIX_ERROR_MESSAGE_ID, "Can't find the suitable file format from this suffix.\nPlease use the other suffix."},
    {SW_SAMP_BIT_ERROR_MESSAGE_ID, "The bits/sample value is not supported for the format."},
    {SW_SAMP_RATE_ERROR_MESSAGE_ID, "The sampling frequency is not supported for the format."},
    {SW_NUM_CHANNEL_ERROR_MESSAGE_ID, "The number of channels is not supported for the format."},
    {SW_PARAMETER_ERROR_MESSAGE_ID, "The value of `%s' is invalid."},
    {SW_MULTIPLE_INSTANCE_ERROR_MESSAGE_ID, "Only single file can be operated simultaneously for this format."},
    
    {SW_NO_LABEL_ERROR_MESSAGE_ID, "There is no label."},
    {SW_SAVE_BY_NORMAL_LABEL_TITLE_ID, "Save By Normal Label"},
    {SW_SAVE_BY_REGION_LABEL_TITLE_ID, "Save By Region Label"},
    {SW_SBL_SAVE_DIR_LABEL_ID, "Save directory"},
    {SW_SBL_NAMING_RULE_NULL_LABEL_ERROR_MESSAGE_ID, "You cannot select this rule because all labels have no string."},
    {SW_SBL_NAMING_WRONG_FORMAT_ERROR_MESSAGE_ID, "Format string is wrong."},
    {SW_SBL_NAMING_RULE_LABEL_ID, "File naming rule"},
    {SW_SBL_NAMING_LABEL_LABEL_ID, "Label string"},
    {SW_SBL_NAMING_DATA_LABEL_ID, "Data string"},
    {SW_SBL_NAMING_ORIG_AND_LABEL_LABEL_ID, "File name + label string"},
    {SW_SBL_NAMING_ORIG_AND_DATA_LABEL_ID, "File name + data string"},
    {SW_SBL_NAMING_AUTOSAVE_LABEL_ID, "Same as autosave"},
    {SW_SBL_NAMING_SERIAL_LABEL_ID, "Serial number"},
    {SW_SBL_NAMING_EDGE_POINTS_LABEL_ID, "Edge points"},
    {SW_SBL_NAMING_CUSTOM_LABEL_ID, "Custom"},
    {SW_SBL_NAMING_CUSTOM_FORMAT_LABEL_ID, "Format for custom naming rule"},
    {SW_SBL_NAMING_REPETITION_SUFFIX_FORMAT_LABEL_ID, "Suffix format in name duplication"},
    {SW_SBL_NAMING_CUSTOM_FORMAT_FIELD_DESC_ID, "%d, %02d, %03d: label serial number, %L: label string, %D: data string, %F: original filename of this file"},
    {SW_SBL_NAMING_REPETITION_SUFFIX_FORMAT_FIELD_DESC_ID, "%d, %02d, %03d: number of duplication count"},
    {SW_SBL_INDEX_FROM_1ST_LABEL_ID, "Serial number is added from 1st label string"},
    {SW_SBL_ILLEGAL_CHAR_TO_SPACE_LABEL_ID, "Replace illegal chars to space"},
    {SW_SBL_DATA_AS_FILENAME_LABEL_ID, "Treat string as file name"},
    {SW_SBL_NO_OVERWRITE_PROMPT_LABEL_ID, "Disable overwrite prompt"},
    {SW_SBL_CREATE_WINDOW_LABEL_ID, "Create new windows for saved files"},
	
    {SW_SAVE_CHANGES_QUESTION_TITLE_ID, "Save Changes"},
    {SW_SAVE_CHANGES_QUESTION_MESSAGE_ID, "Do you want to save changes to \n\"%s\"?"},
    {SW_SAVE_LABEL_CHANGES_QUESTION_MESSAGE_ID, "Do you want to save changes of labels?"},
    {SW_SAVE_REGION_LABEL_CHANGES_QUESTION_MESSAGE_ID, "Do you want to save changes of region labels?"},
    {SW_SAVE_ERROR_CLOSE_QUESTION_MESSAGE_ID, "Can't save this file.\nClose this window anyway?"},
    {SW_SAVE_ERROR_CONTINUE_QUESTION_MESSAGE_ID, "Can't save this file.\nContinue anyway?"},

    {"SW_SAMP_FREQ_CONV_ERROR_MESSAGE", "Can't execute sampling frequency conversion."},
    {"SW_SAMP_FREQ_CONV_FILTER_ERROR_MESSAGE", "Can't create the filter for sampling frequency conversion."},
    
    {SW_ERASE_LABEL_QUESTION_TITLE_ID, "Erase Label"},
    {SW_ERASE_LABEL_QUESTION_MESSAGE_ID, "Really erase the label?\nYou can't undo this processing."},
    
    {SW_UNSUPPORTED_LABEL_QUESTION_TITLE_ID, "Clear Labels"},
    {SW_UNSUPPORTED_LABEL_QUESTION_MESSAGE_ID, "Invalid number of labels in this mode.\nClear all labels?"},
    {SW_UNSUPPORTED_NORMAL_LABEL_QUESTION_TITLE_ID, "Clear Normal Labels"},
    {SW_UNSUPPORTED_NORMAL_LABEL_QUESTION_MESSAGE_ID, "Invalid number of normal labels in this mode.\nClear all normal labels?"},
    {SW_UNSUPPORTED_REGION_LABEL_QUESTION_TITLE_ID, "Clear Region Labels"},
    {SW_UNSUPPORTED_REGION_LABEL_QUESTION_MESSAGE_ID, "Invalid number of region labels in this mode.\nClear all region labels?"},
    
    {SW_STOP_EDIT_QUESTION_MESSAGE_ID, "Really stop editing?"},
    {SW_CLEAR_LABEL_QUESTION_MESSAGE_ID, "Really clear labels?\nYou can't undo this processing."},
    {SW_AUTOSAVE_CLEAR_LABEL_QUESTION_MESSAGE_ID,
	 "Region labels will be cleared before autosaving.\nContinue?\nIf you don't want to do, please save labels before continuing."},
    {SW_TIME_FORMAT_ERROR_MESSAGE_ID, "The time format is wrong."},
    {SW_FIND_DATA_ERROR_MESSAGE_ID, "Can't find data."},
    {SW_FIND_LABEL_NEAR_CURSOR_ERROR_MESSAGE_ID, "Can't find labels near the cursor."},
    {SW_FIND_LABEL_REGION_ERROR_MESSAGE_ID, "Can't find labels in the selected region."},
    {SW_FIND_LABEL_ERROR_MESSAGE_ID, "Can't find labels."},
    {SW_MAXIMUM_VALUE_TOO_SMALL_ERROR_MESSAGE_ID, "Maximum value is too small."},
    {SW_FIND_ACTIVE_LABEL_ERROR_MESSAGE_ID, "Can't find an active label."},
    
    {SW_NEED_RESTART_WARNING_MESSAGE_ID, "This setting will take effect after restarting."},
    {SW_OVERFLOW_WARNING_MESSAGE_ID, "Overflow may happen. \nContinue?"},
    {SW_OVERFLOW_HAPPENED_WARNING_MESSAGE_ID, "Overflow happened."},
    {SW_ASSUME_FLOAT_NORMALIZED_WARNING_MESSAGE_ID, 
	"Maximum value of floating value is assumed to be 1.0.\nContinue?"},
    {SW_SAMP_RATE_CHANGED_WARNING_MESSAGE_ID,
	 "The converted sampling frequency isn't accurate.\nThe sampling frequency is: %.2f"},
    {SW_PROCESSING_WARNING_MESSAGE_ID, "This operation is not allowed while processing."},
    
    {SW_DISPLAY_HELP_ERROR_MESSAGE_ID, "Can't find help file."},
    {SW_INFO_MESSAGE_ID, "spwave version %s\nCopyright(C) Hideki Banno"},

    {SW_FORMAT_TITLE_ID, "Select Format"},
    {SW_SAMP_RATE_LABEL_ID, "Sampling Frequency"},
    {SW_FORMAT_LABEL_ID, "File Format"},
    {SW_CHANNEL_LABEL_ID, "Number of Channel"},
    {SW_BIT_LABEL_ID, "Bits/Sample"},
    {SW_VALUE_LABEL_ID, "Value"},
    {SW_PROPERTY_TITLE_ID, "File Properties"},
    {SW_FILE_PATH_LABEL_ID, "File Path"},
    {SW_PLUGIN_LABEL_ID, "Plugin"},
    {SW_AMPLITUDE_MAX_LABEL_ID, "Max. Amplitude"},
    {SW_AMPLITUDE_MIN_LABEL_ID, "Min. Amplitude"},
    {SW_FILENAME_LABEL_ID, "File Name"},
    {SW_FILE_TYPE_LABEL_ID, "File Type"},
    
    {SW_SELECTION_TAB_TITLE_ID, "Selection"},
    {SW_SELECTION_TAB_POINT_BOX_TITLE_ID, "Point"},
    {SW_SELECTION_TAB_TIME_BOX_TITLE_ID, "Time"},
    {SW_SELECTION_TAB_START_LABEL_ID, "Start"},
    {SW_SELECTION_TAB_END_LABEL_ID, "End"},
    {SW_SELECTION_TAB_LENGTH_LABEL_ID, "Length"},
    {SW_SELECTION_TAB_PLAY_LABEL_ID, "Play"},
	
    {SW_NORMAL_LABEL_LABEL_ID, "Normal Label"},
    {SW_REGION_LABEL_LABEL_ID, "Region Label"},
    
    {SW_UPDATE_LABEL_LABEL_ID, "Update"},
    {SW_SELECT_LABEL_LABEL_ID, "Select"},
    {SW_EDIT_LABEL_LABEL_ID, "Edit"},
    {SW_ERASE_LABEL_LABEL_ID, "Erase"},
    {SW_CAT_LABEL_LABEL_ID, "Concatenate"},
    {SW_PLAY_LABEL_LABEL_ID, "Play"},
    {SW_PREV_LABEL_LABEL_ID, "Previous"},
    {SW_NEXT_LABEL_LABEL_ID, "Next"},
    
    {SW_AMPLIFY_DIALOG_TITLE_ID, "Amplify"},
    {SW_AMPLIFY_RATE_LABEL_ID, "Amplify Rate"},
    {SW_AMPLIFY_DB_LABEL_ID, "Rate in Decibel"},

    {SW_MAXIMIZE_DIALOG_TITLE_ID, "Maximize"},
    {SW_MAXIMIZE_RATE_LABEL_ID, "Maximize Rate"},
    {SW_MAXIMIZE_DB_LABEL_ID, "Rate in Decibel"},
    
    {SW_SAMP_RATE_CONV_DIALOG_TITLE_ID, "Sampling Frequency Conversion"},
    {SW_CHANNEL_CONV_DIALOG_TITLE_ID, "Channel Conversion"},
    {SW_BIT_CONV_DIALOG_TITLE_ID, "Bits/Sample Conversion"},
    {SW_FLOAT_NORMALIZED_LABEL_ID, "Assume that float value is normalized from -1 to 1"},
    {SW_INSERT_PAUSE_DIALOG_TITLE_ID, "Insert Pause"},
    {SW_PAUSE_LABEL_ID, "Pause Length"},
    {SW_CHANGE_VALUE_DIALOG_TITLE_ID, "Change Value"},
    
    {SW_SFC_CUTOFF_LABEL_ID, "Normalized Cutoff"},
    {SW_SFC_SIDELOBE_LABEL_ID, "Sidelobe"},
    {SW_SFC_TRANSITION_LABEL_ID, "Normalized Transition"},
    {SW_SFC_GAIN_LABEL_ID, "Gain"},
    {SW_SFC_TOLERANCE_LABEL_ID, "Tolerance"},
    {SW_SFC_BUFFER_LENGTH_LABEL_ID, "Buffer Length"},
    
    {SW_PREFERENCE_TITLE_ID, "Preference"},
    {SW_USE_DEFAULT_FORMAT_LABEL_ID, "Use the default format in reading"},
    
    {SW_FILE_TAB_LABEL_ID, "File"},
    {SW_LOOK_TAB_LABEL_ID, "Look"},
    {SW_DISPLAY_TAB_LABEL_ID, "Display"},
    {SW_SOUND_TAB_LABEL_ID, "Sound"},
    {SW_LABEL_TAB_LABEL_ID, "Label"},
    {SW_AUTOSAVE_TAB_LABEL_ID, "Autosave"},
    
    {SW_LOOK_LIKE_LABEL_ID, "Look"},
    {SW_LOOK_LIKE_DIMENSION_ID, "like"},
    {SW_CANVAS_FONT_LABEL_ID, "Font for main canvas"},
    {SW_WINDOW_SIZE_LABEL_ID, "Window size"},
    {SW_PRINT_SIZE_LABEL_ID, "Print size"},
    {SW_INFO_AREA_WIDTH_LABEL_ID, "Information area width"},
    {SW_USE_PLAY_COMMAND_LABEL_ID, "Use the play command forcedly"},
    {SW_PLAY_COMMAND_LABEL_ID, "Play command"},
    {SW_AUDIO_DRIVER_LABEL_ID, "Audio driver"},
    {SW_BUFFER_SIZE_LABEL_ID, "Audio buffer size"},
    {SW_PLAY_DRAW_LABEL_ID, "Draw a cursor on playing"},
    {SW_USE_LOOP_PLAY_LABEL_ID, "Use loop play as default"},
    {SW_USE_SYNC_PLAY_LABEL_ID, "Use synchronous play as default"},
    {SW_USE_THREAD_LABEL_ID, "Use threads for processing"},
    {SW_USE_LOWLEVEL_THREAD_LABEL_ID, "Use low level threads"},
    {SW_ALT_CTRL_SWAP_LABEL_ID, "Swap Alt key and Ctrl key of shortcuts"},
    {SW_SCROLL_LEFT_BY_WHEEL_DOWN_LABEL_ID, "Scroll left by wheel down"},
    {SW_USE_TOOL_BAR_LABEL_ID, "Use a tool bar"},

    {SW_DISPLAY_METER_LABEL_ID, "Display a level meter"},
    {SW_DRAW_SELECTION_TIMES_LABEL_ID, "Draw times of a selected region"},
    {SW_DRAW_SELECTION_LENGTH_LABEL_ID, "Draw a length of a selected region"},
    {SW_DRAW_LABEL_LABEL_ID, "Draw labels"},
    {SW_DRAW_SCALE_LABEL_ID, "Draw a scale"},
    {SW_DRAW_GRID_LABEL_ID, "Draw a grid"},
    {SW_PERCENT_AMPLITUDE_LABEL_ID, "Display amplitude in percent"},
    {SW_LOG_FREQUENCY_AXIS_LABEL_ID, "Use logarithmic frequency axis as default"},
    {SW_DRAW_SPECTROGRAM_KEYS_AS_DEFAULT_LABEL_ID, "Draw a piano keyboard for spectrogram as default"},
    {SW_DRAW_SPECTROGRAM_KEYS_RIGHT_LABEL_ID, "Locate the spectrogram keyboard at the right of the spectrogram"},
    {SW_DRAW_HORIZONTAL_KEYS_AS_DEFAULT_LABEL_ID, "Draw a piano keyboard for spectrum as default"},
    {SW_DRAW_HORIZONTAL_KEYS_TOP_LABEL_ID, "Locate the spectrum keyboard at the right of the spectrum"},
    
    {SW_DISPLAY_INFO_AREA_LABEL_ID, "Display the information area as default"},
    {SW_DISPLAY_FREQ_INFO_AREA_LABEL_ID, "Display the information area for frequency data"},
    {SW_LINK_REGION_LABEL_LABEL_ID, "Link a selected label to a selection"},
    {SW_ERASE_LABEL_PROMPT_LABEL_ID, "Always ask before erasing a label"},
    {SW_SHOW_DIALOG_IN_FIRST_LABEL_SAVE_LABEL_ID, "Show Save As dialog in first label save"},
    {SW_ADD_DEFAULT_LABEL_SUFFIX_FOR_SAVE_AS_LABEL_ID, "Add default label suffix in Save As dialog"},
    {SW_LOAD_DEFAULT_LABEL_LABEL_ID, "Load the default label file in the file directory"},
    {SW_DEFAULT_LABEL_SUFFIX_LABEL_ID, "Default label file suffix"},
    {SW_DEFAULT_REGION_LABEL_SUFFIX_LABEL_ID, "Default region label file suffix"},
    
    {SW_AUTOSAVE_DIR_LABEL_ID, "Autosave directory"},
    {SW_AUTOSAVE_ID_PREFIX_LABEL_ID, "Prefix of autosave ID"},
    {SW_AUTOSAVE_ID_TYPE_LABEL_ID, "Autosave ID type"},
    {SW_AUTOSAVE_LABEL_SUFFIX_LABEL_ID, "Label file suffix"},
    {SW_AUTOSAVE_LABEL_FULLPATH_LABEL_ID, "Write the full path into a label file"},
    {SW_AUTOSAVE_DROP_LABEL_ID, "Autosave by drag && drop"},

    {SW_LABEL_DIALOG_TITLE_ID, "Label Dialog"},
    {SW_LABEL_DIALOG_TIME_LABEL_ID, "Time"},
    {SW_LABEL_DIALOG_END_TIME_LABEL_ID, "End"},
    {SW_LABEL_DIALOG_DATA_LABEL_ID, "Data"},
    {SW_LABEL_DIALOG_SYMBOL_LABEL_ID, "Symbol"},
    {SW_LABEL_DIALOG_CHANNEL_LABEL_ID, "Channel"},

    {SW_ANALYSIS_DIALOG_TITLE_ID, "Preference for Analysis"},
    {SW_ANALYSIS_PARAMETER_LABEL_ID, "Parameters"},
    {SW_ANALYSIS_TYPE_LABEL_ID, "Analysis Type"},
    {SW_ANALYSIS_WINDOW_TYPE_LABEL_ID, "Window Type"},
    {SW_ANALYSIS_FFT_LENGTH_LABEL_ID, "Minimum FFT Length"},
    {SW_ANALYSIS_MAX_FFT_LENGTH_LABEL_ID, "Maximum FFT Length"},
    {SW_ANALYSIS_LIFTER_LABEL_ID, "Lifter Length"},
    {SW_ANALYSIS_ATTRIBUTE_LABEL_ID, "Attribute"},
    {SW_ANALYSIS_NEW_WINDOW_LABEL_ID, "Always make a new window"},
    {SW_ANALYSIS_LINEAR_SPECTRUM_LABEL_ID, "Use a linear spectrum (not use decibel)"},
    {SW_ANALYSIS_NORMALIZE_SPECTRUM_LABEL_ID, "Display a normalized spectrum"},
    {SW_ANALYSIS_NORMALIZE_SPECTRUM_MAX_LABEL_ID, "Normalization with a waveform's maximum"},
    {SW_CQT_PARAMETER_LABEL_ID, "CQT Parameters"},
    {SW_CQT_PARAMETER_BINS_PER_OCTAVE_LABEL_ID, "Bins per octave for CQT"},
    {SW_CQT_PARAMETER_MIN_FREQ_LABEL_ID, "Minimum frequency for CQT"},
    {SW_CQT_PARAMETER_MIN_FREQ_BASED_ON_MUSICAL_NOTE_LABEL_ID, "Use a minimum frequency based on musical note"},
    {SW_CQT_PARAMETER_USE_ERB_LABEL_ID, "Use ERB-based frequency warping"},
    {SW_CQT_PARAMETER_BLOCK_MARGIN_FACTOR_LABEL_ID, "Margin factor of block length"},
    {SW_CQT_PARAMETER_BLOCK_TRANSITION_FACTOR_LABEL_ID, "Transition factor for block window"},
    
    {SW_SPECTROGRAM_DIALOG_TITLE_ID, "Spectrogram Setting"},
    {SW_SPECTROGRAM_RANGE_LABEL_ID, "Range (dB)"},
    {SW_SPECTROGRAM_LIMIT_THRESHOLD_LABEL_ID, "Limiting Threshold (dB)"},
    {SW_SPECTROGRAM_SIMPLIFIED_LABEL_ID, "Draw Simplified Spectrogram"},
    {SW_SPECTROGRAM_GRAY_SCALE_LABEL_ID, "Draw Spectrogram with Gray Scale"},
    
    {SW_OPTION_DIALOG_TITLE_ID, "Format Options"},
    
    {SW_INFO_DIALOG_TITLE_ID, "File Metadata"},
    {SW_INFO_DIALOG_TITLE_LABEL_ID, "Title"},
    {SW_INFO_DIALOG_ARTIST_LABEL_ID, "Artist"},
    {SW_INFO_DIALOG_ALBUM_LABEL_ID, "Album"},
    {SW_INFO_DIALOG_ALBUM_ARTIST_LABEL_ID, "Album Artist"},
    {SW_INFO_DIALOG_COMPOSER_LABEL_ID, "Composer"},
    {SW_INFO_DIALOG_LYRICIST_LABEL_ID, "Lyricist"},
    {SW_INFO_DIALOG_GENRE_LABEL_ID, "Genre"},
    {SW_INFO_DIALOG_ID3_VERSION_LABEL_ID, "ID3v2"},
    {SW_INFO_DIALOG_RELEASE_LABEL_ID, "Release"},
    {SW_INFO_DIALOG_TEMPO_LABEL_ID, "Tempo"},
    {SW_INFO_DIALOG_TRACK_LABEL_ID, "Track"},
    {SW_INFO_DIALOG_TRACK_TOTAL_LABEL_ID, "/"},
    {SW_INFO_DIALOG_DISC_LABEL_ID, "Disc"},
    {SW_INFO_DIALOG_DISC_TOTAL_LABEL_ID, "/"},
    {SW_INFO_DIALOG_COPYRIGHT_LABEL_ID, "Copyright"},
    {SW_INFO_DIALOG_PRODUCER_LABEL_ID, "Producer"},
    {SW_INFO_DIALOG_ENGINEER_LABEL_ID, "Engineer"},
    {SW_INFO_DIALOG_SOURCE_LABEL_ID, "Source"},
    {SW_INFO_DIALOG_ISRC_LABEL_ID, "ISRC"},
    {SW_INFO_DIALOG_SOFTWARE_LABEL_ID, "Software"},
    {SW_INFO_DIALOG_SUBJECT_LABEL_ID, "Subject"},
    {SW_INFO_DIALOG_COMMENT_LABEL_ID, "Comment"},
    
    {"SW_GENERATE_DIALOG_TITLE", "Waveform Generate"},
    {"SW_GENERATE_DIALOG_WAVEFORM_TAB_LABEL", "Waveform Setting"},
    {"SW_GENERATE_DIALOG_WAVEFORM_LABEL", "Waveform"},
    {"SW_GENERATE_DIALOG_FREQUENCY_LABEL", "Frequency"},
    {"SW_GENERATE_DIALOG_PHASE_LABEL", "Phase"},
    {"SW_GENERATE_DIALOG_GAIN_LABEL", "Gain (%)"},
    {"SW_GENERATE_DIALOG_GAIN_DB_LABEL", "Gain (dB)"},
    {"SW_GENERATE_DIALOG_DELAY_LABEL", "Delay"},
    {"SW_GENERATE_DIALOG_DURATION_LABEL", "Duration"},
    {"SW_GENERATE_DIALOG_FILE_TAB_LABEL", "File Setting"},
    {"SW_GENERATE_DIALOG_LENGTH_LABEL", "Total Length"},

    {"SW_FILTERING_DIALOG_TITLE", "Filtering"},
    {"SW_FILTERING_DIALOG_FILTER_TYPE", "Filter Type"},
    {"SW_FILTERING_DIALOG_HIGHPASS_CUTOFF", "Highpass Cutoff"},
    {"SW_FILTERING_DIALOG_LOWPASS_CUTOFF", "Lowpass Cutoff"},
    {"SW_FILTERING_DIALOG_TRANSITION", "Transition"},
	
    {"SW_ANCHOR_LABEL", "Anchor"},
    {"SW_MENU_INSERT_ANCHOR_LABEL", "&Insert Anchor"},
    {"SW_MENU_DELETE_ANCHOR_LABEL", "&Delete Anchor"},
    {"SW_MENU_UNDO_ANCHOR_LABEL", "&Undo Anchor Edit"},
    {"SW_MENU_REDO_ANCHOR_LABEL", "&Redo Anchor Edit"},
    {"SW_NO_ANCHOR_ON_CURSOR_WARNING_MESSAGE", "No anchor exists around the cursor."},
    {"SW_ANCHOR_ALREADY_EXIST_WARNING_MESSAGE", "Anchor already exists."},

#if defined(SW_AH_CUSTOM)
#include "swStringDefsAH_C.h"
#endif
    
    {SP_NULL_ID, ""},
};

#ifdef __cplusplus
}  /* Close scope of 'extern "C"' declaration */
#endif
